name: data
on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocessing.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: "https://gbfs.urbansharing.com/oslobysykkel.no/station_status.json "
          downloaded_filename: station_status.json
          axios_config:
            headers:
              - Client-Identifier: https://github.com/Kalli/bysykkel-data
          postprocess: ./postprocessing.js
